<Project>
  <PropertyGroup>
    <Version>0.16.1</Version>
    <IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
    <Product>HP Smart Alternative (HSA)</Product>
    <Authors>HSA</Authors>
    <Description>An alternative to HP Smart for Windows: discover, print, scan, copy and manage printers over network and USB.</Description>
  </PropertyGroup>
</Project>
